# Generated by Django 3.1.4 on 2021-07-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Rejected Auto', 'Rejected Auto'), ('Rejected Manually', 'Rejected Manually'), ('Cheking', 'Cheking'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Published', 'Published'), ('Error', 'Error')], default='Error', max_length=30, verbose_name='Статус')),
                ('unique_proc', models.FloatField(default=-1.0, verbose_name='Процент уникальности')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain_name', models.CharField(default='', max_length=120, verbose_name='Доменное имя')),
                ('content_tag_name', models.CharField(default='', max_length=120)),
                ('content_property_name', models.CharField(default='', max_length=120)),
                ('content_property_value', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='HrefContentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(default='', max_length=120)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.site')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleUniqueUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plagiat_proc', models.FloatField(default=-1.0, verbose_name='Процент плагиата')),
                ('url', models.CharField(default='', max_length=500, verbose_name='URL')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_initial', models.CharField(default='', max_length=30)),
                ('original', models.TextField()),
                ('translation', models.TextField()),
                ('type', models.CharField(choices=[('Абзац', 'Абзац'), ('Абзац-примечание', 'Абзац-примечание'), ('Подзаголовок', 'Подзаголовок'), ('Заголовок', 'Заголовок'), ('Элемент списка', 'Элемент списка'), ('Не определен', 'Не определен')], default='Не определен', max_length=30, verbose_name='Тип')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
            ],
        ),
    ]
