# Generated by Django 3.1.4 on 2021-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='content_property_name',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_property_value',
            field=models.CharField(default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='content_tag_name',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
