# Generated by Django 3.1.4 on 2021-07-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210703_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='content_page',
            field=models.CharField(default='', max_length=250, verbose_name='Страница со списком контента'),
        ),
    ]
