# Generated by Django 3.1.4 on 2021-07-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210704_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='Page',
        ),
        migrations.RemoveField(
            model_name='article',
            name='site',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.page', verbose_name='Страница сайта'),
            preserve_default=False,
        ),
    ]
