# Generated by Django 3.1.4 on 2021-07-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210704_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='Название статьи'),
        ),
    ]
