# Generated by Django 3.1.4 on 2021-07-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='unique_proc',
            new_name='original_unique_proc',
        ),
    ]
