# Generated by Django 3.1.4 on 2021-07-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210704_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='original_unique_proc',
            field=models.FloatField(default=-1.0, verbose_name='Процент уникальности оригинала'),
        ),
    ]
