# Generated by Django 3.1.4 on 2021-07-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210704_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleitem',
            old_name='tag_initial',
            new_name='tag',
        ),
    ]
